FROM node:20-alpine

WORKDIR /app

COPY backend/package*.json ./backend/
WORKDIR /app/backend
RUN npm install

WORKDIR /app
COPY backend ./backend
COPY common ./common

WORKDIR /app/backend
RUN npm run build

EXPOSE 4000
CMD ["node", "dist/server.js"]
